--- Error Page Not Found



































































































getgenv().Stack=true;getgenv().MethodType="Melee"getgenv().Mode="Cyborg"getgenv().HitsPerSecond=500;getgenv().FarmNearest=true;getgenv().TweenRotate=true;getgenv().TweenSpeed=60;getgenv().AntiKick=true;local a={"Pika-Pika User","Mera-Mera User","Hie-Hie User","Dungeon Kiribachi User","Dungeon Attacker","Dungeon 1SS User","Dungeon Gun User","Dungeon Katana User"}spawn(function()while true do if getgenv().Stack then for b,c in ipairs(workspace.NPCs:GetChildren())do if c:FindFirstChild("HumanoidRootPart")and table.find(a,c.Name)then local d={[1]="damage",[2]={},[3]=getgenv().MethodType,[4]={1,"Ground",getgenv().Mode},[5]=true,[6]=c.HumanoidRootPart.CFrame}for e=1,getgenv().HitsPerSecond do table.insert(d[2],c.HumanoidRootPart)end;game:GetService("ReplicatedStorage").Events.CombatRegister:InvokeServer(d)end end end;task.wait()end end)local f=game:GetService("TweenService")local g=game:GetService("RunService")local h=game:GetService("Players")local i=h.LocalPlayer;local j=i.Character.HumanoidRootPart;function TweenPlayer(k)local l=i.Character and i.Character.PrimaryPart;if not l then return warn('Teleport: No root part')end;local m;if typeof(k)=='Vector3'then m=k elseif typeof(k)=='CFrame'then m=k.Position else return warn('Teleport: Invalid position type')end;local function n()for o,p in pairs(i.Character:GetDescendants())do if p:IsA("BasePart")and p.CanCollide==true then p.CanCollide=false end end end;local q=getgenv().TweenSpeed;local r=(m-l.Position).Magnitude;local s=TweenInfo.new(r/q,Enum.EasingStyle.Linear,Enum.EasingDirection.InOut)local t=typeof(k)=='CFrame'and k or CFrame.new(k)local u=f:Create(l,s,{CFrame=t})local v=Instance.new("BodyGyro")v.Parent=l;v.Name="BodyGyrozz"v.MaxTorque=Vector3.new(0,math.huge,0)v.CFrame=CFrame.new(l.Position,m)local w=g.Stepped:Connect(n)local x=Instance.new("BodyVelocity")x.Parent=l;x.Name="BodyVelocityzz"x.MaxForce=Vector3.new(0,math.huge,0)x.Velocity=Vector3.new(0,0,0)u:Play()u.Completed:Wait()return u end;function TweenRotate(y,z)if not y or not y.PrimaryPart then warn("Invalid object or nil")return end;local A=y.PrimaryPart.Position;local B=A+Vector3.new(0,17,0)TweenPlayer(CFrame.new(B))end;spawn(function()while getgenv().TweenRotate and task.wait(0.1)do for b,C in pairs(workspace.NPCs:GetChildren())do if C and C:FindFirstChild("HumanoidRootPart")and table.find(a,C.Name)then local D=1.5;TweenRotate(C,D)end end end end)spawn(function()while true do task.wait(1.2)if getgenv().AntiKick then local E=game.Players.LocalPlayer;local F=E.Character;local G=F and F.PrimaryPart;local H="Geppo"local I={["cf"]=CFrame.new(G.Position.X,G.Position.Y,G.Position.Z),["char"]=game.Players.LocalPlayer.Character}if getgenv().AntiKick==true then game:GetService("ReplicatedStorage").Events.Skill:InvokeServer(H,I)end end end end)print("Auto Dungeon Working")
